### ISSUE TITLE
SPARQL: check syntax for triplestoreswap

### ISSUE THREAD

**Issue by jefferya** [cwrc/cwrc_migration_batch#2]
To Test:

* drush cwrc_migration_batch_validate

https://github.com/cwrc/cwrc_migration_batch/blob/c9fb796316b414d7d59e760f717f7d75b2ce60a8/cwrc_migration_batch.drush.inc#L1940-L1958

**Comment by joelacummings** [comment]
This seems just fine and uses prefixes, but check the FROM as mentioned in the previous issue.

**Comment by joelacummings** [comment]
Looking at this again it would appear the other examples simply did not use prefixes and you placed the URI within the query and they were full URIs which would likely make them ok.
